### ISSUE TITLE
About homography warping

### ISSUE THREAD

**Issue by chaytonmin** [kwea123/CasMVSNet_pl#11]
I find that the homography warping codes of cascade_pl and original cascade are different. Is the homography warping code of original cascade wrong?
cascade_pl:
![1](https://user-images.githubusercontent.com/40260488/83118901-8f556900-a101-11ea-98b2-a6f842ce5a97.PNG)
original cascade:
![2](https://user-images.githubusercontent.com/40260488/83118913-94b2b380-a101-11ea-8242-24ee69a46e36.PNG)

**Comment by kwea123** [comment]
They are actually "mathematically" the same. If I denote `d` as `depth_values`, then
He uses `R(uv1)d + T`
I use `R(uv1) + T/d`
to compute the projected `xyz` coordinates.
Given that `xyz` are afterwards projected to pixel coordinate `u'v'`, which divides by the depth again (my line with comment "divide by depth"; his `proj_xy`), these two formulae become the same (in fact any other constant factor would be fine). The sole difference might be due to small numerical rounding errors.

The reason why I divide by `d` first is that I tried mixed precision training (aka fp16) so I had to keep the range within the max value 65504. As a result mixed precision training works and we can double the batch size, but I find the speed to be slower in contrast to normal findings... so I still disable mixed precision training by default [here](https://github.com/kwea123/CasMVSNet_pl/blob/master/opt.py#L69), but left this part as it is because as I said above the numeric result is the same.

**Comment by chaytonmin** [comment]
> They are actually "mathematically" the same. If I denote `d` as `depth_values`, then
> He uses `R(uv1)d + T`
> I use `R(uv1) + T/d`
> to compute the projected `xyz` coordinates.
> Given that `xyz` are afterwards projected to pixel coordinate `u'v'`, which divides by the depth again (my line with comment "divide by depth"; his `proj_xy`), these two formulae become the same (in fact any other constant factor would be fine). The sole difference might be due to small numerical rounding errors.
> 
> The reason why I divide by `d` first is that I tried mixed precision training (aka fp16) so I had to keep the range within the max value 65504. As a result mixed precision training works and we can double the batch size, but I find the speed to be slower in contrast to normal findings... so I still disable mixed precision training by default [here](https://github.com/kwea123/CasMVSNet_pl/blob/master/opt.py#L69), but left this part as it is because as I said above the numeric result is the same.

Thanks for your reply!

**Comment by phongnhhn92** [comment]
> They are actually "mathematically" the same. If I denote `d` as `depth_values`, then
> He uses `R(uv1)d + T`
> I use `R(uv1) + T/d`
> to compute the projected `xyz` coordinates.
> Given that `xyz` are afterwards projected to pixel coordinate `u'v'`, which divides by the depth again (my line with comment "divide by depth"; his `proj_xy`), these two formulae become the same (in fact any other constant factor would be fine). The sole difference might be due to small numerical rounding errors.
> 
> The reason why I divide by `d` first is that I tried mixed precision training (aka fp16) so I had to keep the range within the max value 65504. As a result mixed precision training works and we can double the batch size, but I find the speed to be slower in contrast to normal findings... so I still disable mixed precision training by default [here](https://github.com/kwea123/CasMVSNet_pl/blob/master/opt.py#L69), but left this part as it is because as I said above the numeric result is the same.

Can you explain more about this mixed precision training ? So you said by enabling the mixed precision training (FP16 and FP32) then we can double the batch_size right ? So how can it make the training slower ? I initial thought is that if we double the batch size then we can reduce the half of number of training epoch ? Another concern is how does the overall performance decrease if we enable this mix precision training ?

**Comment by kwea123** [comment]
Yes by doubling the batch size the number of iterations is halved, but at the same time I observed that the speed for each iteration was also slower (than two times of the original speed), so in total it makes training slower. I suspect that it's due to some operations that run slower using fp16, but I didn't dig deeper into this problem. I didn't run full training, but as I can remember it has almost the same training curve for the first 2-3 epochs as fp32. You can experiment by yourself by setting this `--use_amp` argument.

The reason I attempted for fp16 training was because I wanted to increase the batch size in order to increase the performance (the accuracy score, etc, not the speed), but as my little experiment shows, it neither improves the score nor increases the speed, so I disabled it.
