### ISSUE TITLE
A question when test on dtu

### ISSUE THREAD

**Issue by LuckyOne09** [kwea123/CasMVSNet_pl#29]
Hi, I have a question when I test on dtu dataset.
I specify self.img_wh of DTUDataset as (640, 512)(in other words, same as training image size). I think ```intrinsics``` read from ```self.root_dir/Cameras/{vid:08d}_cam.txt```will be same as ```intrinsics``` read from ```self.root_dir/Cameras/train/{vid:08d}_cam.txt``` after line 64 in dtu.py.
However, they are not same.

I print  ```intrinsics``` after line 64:
```
[[289.233      0.        82.3204  ]
 [  0.       307.5392    66.034134]
 [  0.         0.         1.      ]]
```
while ```intrinsics``` read from ```self.root_dir/Cameras/train/{vid:08d}_cam.txt```  is:
```
361.54125      0.0      82.900625 
0.0      360.3975      66.383875 
0.0      0.0      1.0  
```

I don't figure out that what's wrong with my thoughts. Could you give me some hints on it? Please forgive me if it is a stupid question. Very thanks for your kindness.

**Comment by kwea123** [comment]
In the MVSNet paper, he described how the training images are generated. They are not direct resize but a resize followed by a crop. I have comments in the code too:
https://github.com/kwea123/CasMVSNet_pl/blob/c94e7b00a6fd73df37117ddee1945fe99a43138d/datasets/dtu.py#L93-L97

Therefore, the intrinsics are not the same, because cropping changes the parameters differently. My test code uses resizie only.

**Comment by LuckyOne09** [comment]
Thank you! It helps me a lot.
