### ISSUE TITLE
Zero points in output .ply

### ISSUE THREAD

**Issue by KevinCain** [kwea123/CasMVSNet_pl#9]
When running CasMVSNet_pl on my own data, I'm able to run inference and point fusion without errors, but the resulting .ply contains zero points:

```ply
format binary_little_endian 1.0
element vertex 0
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
end_header
```

Using the same input, here's a reference snapshot of a .ply result computed with the basis [Cascade Stereo](https://github.com/alibaba/cascade-stereo) method:

![image](https://user-images.githubusercontent.com/5424003/78280116-9176bf00-74e6-11ea-876c-848e2bb6ee83.png)

Depth computation looks fine, but perhaps during fusion the camera intrinsics u0 + v0 in matrix K are not preserved?
![image](https://user-images.githubusercontent.com/5424003/78280802-a9027780-74e7-11ea-8fcb-fb88b4e41d66.png)

Any thoughts are welcome!

**Comment by kwea123** [comment]
Your own data is some modified version of DTU right? In `eval.py` it just reads the projection matrix from the dataloader and doesn't modify.
https://github.com/kwea123/CasMVSNet_pl/blob/2df43712c3aa1bbe422b3edaae560e1b5152bd01/eval.py#L106-L110
So you need to verify that the projection matrix is correctly computed and read from the dataloader

**Comment by KevinCain** [comment]
I agree that `eval.py` loads the K matrices verbatim but from a cursory look at the fusion code could not verify that intrinsics are preserved, which might lead to the zero point output.

For my test data, I start with DTU images, but compute the intrinsics (and extrinsics) with an SfM method and the pair data separately. As shown above, the canonical Cascade Stereo paper's code returns a sane point cloud given the camera+pair data I've created, however CasMVSNet_pl returns an empty point set.

**Comment by kwea123** [comment]
Did you try to modify the parameters in `eval.py`? Like the `--conf` and `--min_geo_consistent`. I suspect that maybe the confidence is low so everything is ignored by the default `conf=0.999`, maybe try to set it to a lower value?

**Comment by KevinCain** [comment]
Thanks, @kwea123, I should have checked the common parameters first.

I adjusted pixel confidence value from 0.999 to 0.9 -> 0.5, all with 0 points output:
![image](https://user-images.githubusercontent.com/5424003/78365608-4e235b80-758d-11ea-9411-734947493834.png)

I verified that I indeed have (5) matching views for each entry in `pair.txt`, as per the default value in `eval.py'.

Since the depth maps seem relatively sane, I still suspect the fusion step and will have a look. Any other thoughts welcome!

**Comment by kwea123** [comment]
Hi, I just checked the files you sent me. Actually there's more to modify in the code..
I don't know how you generate the camera intrinsics and the extrinsics, but anyway, there are always two things to verify!

1.  What is the depth and extrinsics scale?
2.  The intrinsics corresponds to what image size?

Then you can modify the code correctly if you can answer the questions above:

1. On the last line of the `_cam.txt` files and the extrinsics parameters, it seems that the depth is now scaled to about 1/100 of the original scale: originally it was 425 but your file has ~4.00, and naturally the `depth_interval` should decrease as well, which is shown as `0.0341576` in the file. Originally it was `2.65`, so that's one thing to modify here.

2. By checking the image size you sent me, they are of 800x600, so the intrinsics should be of this size (instead of the original 1600x1200), therefore, when modifying the intrinsics due to resizing, you need to compute the ratio between 800 and 600, not 1600 and 1200 here:
https://github.com/kwea123/CasMVSNet_pl/blob/2df43712c3aa1bbe422b3edaae560e1b5152bd01/datasets/dtu.py#L62-L64

Lastly it seems that with your cropped images, the depth confidence tend to be low, so setting a lower confidence threshold and also fewer consistent view constraint will yield more points;

Finally the things I did were:

1. Change image, cam load paths
2. change 1600 to 800, 1200 to 600 in the above code snippet
3. use this command to evaluate:
```
python eval.py \
--dataset_name dtu \
--root_dir sample \
--split test \
--ckpt_path ckpts/exp2/_ckpt_epoch_10.ckpt \
--num_groups 1 \
--img_wh 800 576 \
--scan scan9 \
--save_visual \
--depth_interval 0.0341576 \
--conf 0.8 --min_geo_consistent 3
```

this gives me 28M points
![Screenshot from 2020-04-03 23-05-43](https://user-images.githubusercontent.com/11364490/78369246-d93d3980-75ff-11ea-8868-3b0c57f8044b.png)

Hope now you know what to check when using your own data

**Comment by KevinCain** [comment]
A big thank you @kwea123 for your patient, detailed response, I am happily able to duplicate your results above. I had noted the image size differences and that the depth interval generated by my code was x100 different, but was still setting the interval too high.

Tuning the confidence and depth interval yields slightly higher point counts (30M+ points).

I can confirm that CasMVSNet_pl uses only **3094MB GPU RAM vs. 4480MB GPU RAM** with the model trained on BlendedMVS data for Cascade Stereo using the same input data, which is impressive; see the snapshot below for results. The DTU-based model consumed 4106MB GPU RAM with the same input, and provided a bit more completeness as per a previous thread.

![image](https://user-images.githubusercontent.com/5424003/78397828-ef2b0a00-75bf-11ea-979e-1ac0f6be59c5.png)


Thanks again!
